### PR TITLE
fixed cget function and added get function

### PR DESCRIPTION
**Pull request by walkloud**
I added a get function - and modified cget to take a disk_path and tape_file

I am not sure if you use cget in a way inconsistent with my changes - I just realized - please consider carefully.  I did not see any use of cget in your utils - but - it did not work as I have been using it via command line - i.e. I still need to make sure I cd to the local directory and then get the full path

I just realized - get will not respect the time stamp of the tape file, but will leave NOW as the time on disk.

### CODE REVIEW

**Comment by evanberkowitz** [comment]
Is timestamp preservation something we want?  From reading https://docs.scinet.utoronto.ca/index.php/HPSS it looks like we can pass get/cget the `-p` flag, which would preserve the timestamp.

**Comment by walkloud** [comment]
let me test with `get`.  Our implementation of `cget` does preserve time stamps - thanks for reading the docs!

**Comment by walkloud** [comment]
manually tested - adding `-p` indeed preserves the time stamp.  I wrapped it in an option `preserve_time=True` argument to `get()`

**Review by evanberkowitz — APPROVED** [review]
Makes sense to have the timestamp preservation be default, good thinking.

**Pull request merged**
